CREATE TABLE CITY(
   CITY_ID int(10) NOT NULL AUTO_INCREMENT,
   NAME varchar(100) NOT NULL,
   PRIMARY KEY ( CITY_ID )
);

CREATE TABLE USERS(
   USER_ID int(10) NOT NULL AUTO_INCREMENT,
   LOGIN varchar(100) NOT NULL,
   EMAIL varchar(255),
   CITY_ID int(10),
   PRIMARY KEY ( USER_ID )
);